#include <iostream>
#include <string>
#include "tgmenu.h"

using namespace std;

int tgpro()
{
string h = "The Gifted    -    Prologue    -    Page ";        // Chapter Header
string p = "Prologue    -    Page ";        // Page header
string t = "    ";        // 4 space tab
int n = 1;
	system ("cls");
	cout << h;
	cout << n++;
	cout << "\n" << endl;
	cout << "It was a pleasant, sunny, day. David had decided to go for a long walk in a" << endl;
	cout << "rather large, nearby park. It was located in the country, surrounded by woods," << endl;
	cout << "and well kept. David had traveled there by foot, and was enjoying the warm" << endl;
	cout << "summer's weather." << endl;
	cout << t << "On his way there, he had greeted several people he knew, and a couple he" << endl;
	cout << "did not. The good thing about the park he went to was people were usually" << endl;
	cout << "friendly there. He also enjoyed walking to the park because he saw a variety of" << endl;
	cout << "them every day just getting there." << endl;
	cout << t << "David lived in a small, clean country town, so getting around was easy, and" << endl;
	cout << "since most people still went for walks there was not much traffic. However," << endl;
	cout << "like everywhere else, the town was growing, and walking was becoming less and" << endl;
	cout << "less frequent. Most people in this town realized this as the years passed, but" << endl;
	cout << "did not like to talk about it." << endl;
	cout << t << "On this day, David's life was about to take a turn for the better, though" << endl;
	cout << "he did not know until later; or, rather until he saw her." << endl;
	cout << t << "She was a woman with beautiful dark blond hair, sitting on a park bench and" << endl;
	cout << "reading what seemed to be a semi-interesting book, at least that was what the" << endl;
	cout << "expression on her face said. David decided it was a good time to go over and" << endl;
	cout << "introduce himself to her." << endl;
	cout << t << "David approached the woman and simply said, \"Hi.\"" << endl;
	cout << t << "The woman looked up at David, and their eyes met. Her dark blue eyes" << endl;
	cout << "immediately captured David's heart; as did his kind gaze capture hers." << endl;
	system ("pause");
	system ("cls");
	cout << p;
	cout << n++;
	cout << "\n" << endl;
	cout << t << "\"Mind if I sit down?\" David asked the woman, keeping his cool." << endl;
	cout << t << "\"No, not at all,\" said the woman." << endl;
	cout << t << "David sat next to the woman." << endl;
	cout << t << "\"So, what are you reading?\" asked David." << endl;
	cout << t << "\"Nothing important,\" said the woman, putting the book in her purse." << endl;
	cout << t << "\"I'm David,\" he said." << endl;
	cout << t << "\"Maria,\" said the woman extending her hand." << endl;
	cout << t << "David took Maria's hand in a friendly greeting." << endl;
	cout << t << "\"Want to go for a walk?\" David asked Maria." << endl;
	cout << t << "\"Sounds nice,\" said Maria." << endl;
	cout << "    The two got up for a walk in the park. While they were walking, they talked" << endl;
	cout << "to each other." << endl;
	cout << t << "\"So,\" said David, after a while, \"You don't come here often, do you?\"" << endl;
	cout << t << "\"I just moved here a couple of weeks ago,\" said Maria." << endl;
	cout << t << "\"Are you from out of town?\" asked David." << endl;
	cout << t << "\"No,\" said Maria, \"Just from the north end.\"" << endl;
	cout << t << "\"I moved here about five years ago,\" said David." << endl;
	cout << t << "\"Where are you from?\" asked Maria." << endl;
	cout << t << "\"Berkley,\" said David, \"Nice town; small and quiet.\"" << endl;
	cout << t << "\"Where's Berkley?\" asked Maria." << endl;
	cout << t << "\"About a hundred and fifty miles from here,\" said David." << endl;
	cout << t << "\"So why did you move here?\" asked Maria." << endl;
	system ("pause");
	system ("cls");
	cout << p;
	cout << n++;
	cout << "\n" << endl;
	cout << t << "\"Family reasons,\" said David, \"My father had become very sick, but he's" << endl;
	cout << "better now. I guess the reason I didn't move back was that I got used to it" << endl;
	cout << "here. Besides now I own my own business here, I can't just leave it.\"" << endl;
	cout << t << "\"No,\" said Maria, \"you can't.\"" << endl;
	cout << t << "\"So,\" said David, \"are you planning on staying in this part?\"" << endl;
	cout << t << "\"Yes I am,\" said Maria, \"This is a much nicer part of the city. It's not" << endl;
	cout << "really developed, it's quieter, and the people seem friendlier here.\"" << endl;
	cout << t << "\"I know,\" said David, \"There's a lot of gang activity and drugs up the" << endl;
	cout << "north end.\"" << endl;
	cout << t << "\"So how often do you come here?\" asked Maria." << endl;
	cout << t << "\"Almost every day,\" answered David." << endl;
	cout << t << "\"Good,\" said Maria, \"Then I guess we'll be seeing each other a lot.\"" << endl;
	cout << t << "\"You seem like a nice person,\" said David, \"I think we're going to get" << endl;
	cout << "along just fine.\"" << endl;
	cout << t << "\"Thank you,\" said Maria, \"You seem nice too.\"" << endl;
	cout << t << "David spotted some pretty flowers by some bushes, picked them, and then" << endl;
	cout << "gave them to Maria. Maria accepted the flowers, thinking that it was romantic" << endl;
	cout << "and a nice gesture on David's part." << endl;
	cout << t << "\"How nice,\" said Maria as she accepted the flowers, \"They're lovely.\"" << endl;
	cout << t << "The two walked and talked together and when it was time to leave, they" << endl;
	cout << "exchanged numbers." << endl;
	cout << t << "David and Maria started dating shortly after, and quickly grew close. They" << endl;
	system ("pause");
	system ("cls");
	cout << p;
	cout << n++;
	cout << "\n" << endl;
	cout << "found they had a lot in common with each other. They liked the same kinds of" << endl;
	cout << "movies and music. They both liked going for long drives in the country, they" << endl;
	cout << "even liked the same plays." << endl;
	cout << t << "David often talked to his mother about Maria and she began to get a good" << endl;
	cout << "idea of what she was like. From the way David spoke of Maria his mother already" << endl;
	cout << "liked Maria." << endl;
	cout << t << "As the days went on David and Maria began seeing each other regularly. They" << endl;
	cout << "usually saw each other on Friday nights and Saturdays. They went to church on" << endl;
	cout << "Sundays, and David worked Sunday afternoons." << endl;
	cout << t << "David owned his own business that dealt with hardware and supplies. Maria" << endl;
	cout << "would often visit him and sometimes help on Saturdays and Sundays. It was a way" << endl;
	cout << "of spending time with each other and when the workday was done, they would hang" << endl;
	cout << "out together and go places until it got late." << endl;
	cout << t << "Though David was close to his parents, he was not as close to his father as" << endl;
	cout << "he was to his mother. He would visit his parents every other week on Sunday," << endl;
	cout << "usually in the afternoon, and would not open his business on those days." << endl;
	cout << t << "Maria worked as a manager at a retail store and had good hours. She worked" << endl;
	cout << "Monday through Fridays from opening time to about four-thirty and often late in" << endl;
	cout << "the early part of the week. Fridays was usually the easiest day for her as she" << endl;
	cout << "often was able to leave early." << endl;
	cout << t << "David and Maria were getting along very well, and three months after they" << endl;
	cout << "started seeing each other steadily, David decided to introduce Maria to his" << endl;
	system ("pause");
	system ("cls");
	cout << p;
	cout << n++;
	cout << "\n" << endl;
	cout << "parents." << endl;
	cout << t << "One day David called his parents from his home. The phone on the other end" << endl;
	cout << "rang and David's mother answered." << endl;
	cout << t << "\"Hello?\" she answered." << endl;
	cout << t << "\"Hi, Mom,\" said David." << endl;
	cout << t << "\"Hi, Dave,\" said his mother, \"How are things?\"" << endl;
	cout << t << "\"Fine,\" said David, \"Do you know how I'm seeing Maria?\"" << endl;
	cout << t << "\"Yes,\" said David's mother." << endl;
	cout << t << "\"Well,\' said David, \"I'd like you to meet her.\"" << endl;
	cout << t << "\"I almost feel like I already have,\" said David's mother, \"When can the two" << endl;
	cout << "of you come over? We'll have dinner, and talk.\"" << endl;
	cout << t << "David's mother had already heard a lot about Maria and was eager to meet" << endl;
	cout << "her in person. If Maria were half as nice as David portrayed, they would get" << endl;
	cout << "along just fine." << endl;
	cout << t << "\"I'll have to talk to Maria to make sure,\" said David, \"but I'd say" << endl;
	cout << "probably sometime next week.\"" << endl;
	cout << t << "\"Well,\" said David's mother, \"Tuesday or Thursday night is fine with us.\"" << endl;
	cout << t << "\"I'll talk to Maria,\" said David, \"but I'm more than sure that Thursday" << endl;
	cout << "will be perfect.\"" << endl;
	cout << t << "\"Good,\" said David's mother, \"Hope to see you then.\"" << endl;
	cout << t << "David talked to his mother for a while, and then called Maria." << endl;
	cout << t << "\"Hello?\" she answered." << endl;
	system ("pause");
	system ("cls");
	cout << p;
	cout << n++;
	cout << "\n" << endl;
	cout << t << "\"Guess who,\" said David, playfully." << endl;
	cout << t << "Maria immediately knew who it was by the sound of David's voice." << endl;
	cout << t << "\"Hi, David,\" said Maria in a 'Glad to hear you' tone." << endl;
	cout << t << "\"What are you doing this week?\" asked David." << endl;
	cout << t << "\"Well,\" said Maria, \"I'm always free Fridays, you know that.\"" << endl;
	cout << t << "\"How about Tuesday or Thursday night,\" said David, \"say, after four?\"" << endl;
	cout << t << "\"Tuesday I've got to work late,\" said Maria, \"and Thursday I was going out" << endl;
	cout << "with some friends, why?\"" << endl;
	cout << t << "\"I was thinking,\" said David, \"Would you like to meet my parents?\"" << endl;
	cout << t << "There was a thoughtful silence that lasted but a short moment." << endl;
	cout << t << "\"Sure,\" said Maria, \"I'll just tell my friends next week.\"" << endl;
	cout << t << "\"Are you sure?\" asked David." << endl;
	cout << t << "\"Yah, I'm sure,\" said Maria, \"I can always hang out with the girls another" << endl;
	cout << "time. This is important. They really want to meet me?\"" << endl;
	cout << t << "\"Are you kidding?\" asked David, \"It's all my mother talks about. She's" << endl;
	cout << "always asking 'David, when are you going to bring Maria by?' So I figured this" << endl;
	cout << "week would be perfect. I just don't want to ruin your plans.\"" << endl;
	cout << t << "\"You're not,\" said Maria, \"If your parents want to meet me, why did you" << endl;
	cout << "wait?\"" << endl;
	cout << t << "\"Truthfully?\" asked David, \"I wanted to see if our relationship was strong" << endl;
	cout << "enough. I feel it has reached a level where we will be together for a long" << endl;
	cout << "time, if not longer, so I think now's the time. After all, if I didn't think" << endl;
	system ("pause");
	system ("cls");
	cout << p;
	cout << n++;
	cout << "\n" << endl;
	cout << "our relationship was that serious, I probably wouldn't be doing this.\"" << endl;
	cout << t << "\"So,\" said Maria, \"you feel our relationship is long-term.\"" << endl;
	cout << t << "\"The way I see it,\" said David, \"is we have something special between us," << endl;
	cout << "and I'm not about to let it go. I've never felt this way about anyone before" << endl;
	cout << "and I really feel it's going to last. Besides, I believe we'll always at least" << endl;
	cout << "be friends, if not more.\"" << endl;
	cout << t << "\"That's sweet,\" said Maria, \"I love you too, and I feel the same way. You" << endl;
	cout << "can tell your parents Thursday night is perfect.\"" << endl;
	cout << t << "\"What time?\" asked David." << endl;
	cout << t << "\"Five should be fine,\" said Maria." << endl;
	cout << t << "\"Great,\" said David, \"I'll pick you up then.\"" << endl;
	cout << t << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	system ("pause");
	system ("cls");
	cout << p;
	cout << n++;
	cout << "\n" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	system ("pause");
	system ("cls");
	cout << p;
	cout << n++;				// page 9
	cout << "\n" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	system ("pause");
	tgmenu();
	return 0;
}
